### ISSUE TITLE
Jest tests give SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by saschwarz** [reststate/reststate-vuex#162]
Hi,

I've added `@restate/restate-vuex` to our project and it works perfectly. Unfortunately, our jest tests are failing on the import of the module into the project:

```javascript
    /app/node_modules/@reststate/vuex/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { resourceModule, mapResourceModules } from './src/reststate-vuex';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import getters from './getters'
      2 | import httpClient from '@/services/JsonAPIService'
    > 3 | import { mapResourceModules } from '@reststate/vuex';
        | ^
      4 | import merge from 'lodash/merge'
      5 | 
      6 | const modules = merge(

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/state/modules/portfolios/index.js:3:1)

```

Since the app builds w/o errors I'm assuming I have something wrong in the jest configuration and was hoping you might have some pointers on property configuring jest for this library.

`jest.config.js`
```javascript
module.exports = {
  moduleFileExtensions: ['js', 'jsx', 'json', 'vue'],
  transform: {
    '^.+\\.vue$': 'vue-jest',
    '.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$':
      'jest-transform-stub',
    '^.+\\.jsx?$': 'babel-jest'
  },
  transformIgnorePatterns: ['/node_modules/'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1'
  },
  snapshotSerializers: ['jest-serializer-vue'],
  testMatch: [
    '<rootDir>/(tests/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx))'
  ],
  collectCoverageFrom: ["**/*.{js,vue}", "!**/node_modules/**", "!**/tests/**", "!**/coverage/**", "!*config.js"],
}
```

Thanks for any assistance!

**Comment by saschwarz** [comment]
I had to change:

`  transformIgnorePatterns: ['/node_modules/'],`

to:

`  transformIgnorePatterns: [],`

I thought I'd tried that permutation before opening this issue. Sorry to have bothered you.
