### ISSUE TITLE
How to use with Jest?

### ISSUE THREAD

**Issue by geoidesic** [reststate/reststate-vuex#281]
When I try to use this module with Jest I get errors:
```
● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/me/projects/MyProject/node_modules/@reststate/vuex/src/deepEquals.js:2
    export default function deepEquals() {
    ^^^^^^

    SyntaxError: Unexpected token export

      2 | import { ResourceClient } from "src/utils/reststate-vuex/client";
      3 | // @todo for production
    > 4 | import deepEquals from "@reststate/vuex/src/deepEquals";
        | ^
      5 | const STATUS_INITIAL = "INITIAL";
      6 | const STATUS_LOADING = "LOADING";
      7 | const STATUS_ERROR = "ERROR";

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1295:14)
      at Object.<anonymous> (src/utils/reststate-vuex/index.js:4:1)
```

Do you have a fix for this? I'm not sure what to put in "transformIgnorePatterns" to fix this.

**Comment by CodingItWrong** [comment]
FYI, this library will be unmaintained going forward.

If you need new features or fixes, I recommend forking the repo and making changes, or finding an alternate library that meets your needs.
